# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

ATOSHeader atos_header
geometry_msgs/PoseStamped pose
geometry_msgs/TwistStamped velocity
geometry_msgs/AccelStamped acceleration
ObjectDriveDirection drive_direction
ReadyToArm ready_to_arm
ObjectErrorType error_status
ObjectState object_state
